export const LINKS = {
  github: 'https://github.com/1046prt',
  linkedin: 'https://linkedin.com/in/1046prt',
  twitter: 'https://x.com/1046prt',
  kaggle: 'https://www.kaggle.com/prt1046',
  email: 'mailto:rajprakash1046@gmail.com',
  phone: 'tel:+919508015377',
  resume: 'https://drive.google.com/file/d/1_sRECd19TUycxLQmA_pVV3DydlgF_Na9/view?usp=sharing',
  blog: '/blog',
  home: '/',
  projects: '#projects',
  contact: '#contact',
  about: '#about',
  skills: '#skills',
};
