export const LINKS = {
  github: 'https://github.com/1046prt',
  linkedin: 'https://linkedin.com/in/1046prt',
  medium: 'https://medium.com/@1046prt',
  researchgate: 'https://www.researchgate.net/profile/Prakash-Raj-18',
  email: 'mailto:rajprakash1046@gmail.com',
  phone: 'tel:+919508015377',
  resume: 'https://drive.google.com/file/d/1_sRECd19TUycxLQmA_pVV3DydlgF_Na9/view?usp=sharing',
  blog: '/blog',
  home: '/',
  projects: '#projects',
  contact: '#contact',
  about: '#about',
  skills: '#skills',
};
